### ISSUE TITLE
git client install resource

### ISSUE THREAD

**Issue by leshkinski** [rsWinAutomationSupport/rsGit#12]
Issue refers to creation of a dedicated resource to install Git client on a node without relying on boostrap mechanism, which will no longer deploy git client. Suggested name - "rsGitInstall".

**Comment by jonathan-madison** [comment]
Would it be more appropriate to use the Package resource in this instance and use DependsOn with any client DSC usage?

**Comment by leshkinski** [comment]
Yes, now that we are going to default to WMF 5.0 and the built-in package management facilities, we won't need this one :) Closing issue
