### ISSUE TITLE
Implement Test-TargetResource logic correctly

### ISSUE THREAD

**Issue by leshkinski** [rsWinAutomationSupport/rsGit#6]
**Problem Description:** 
Test-TargetResource for rsGit always returns 'false' and is missing any logic to verify if a repo requires an update
 
**Versions affected:** ALL
 
**Steps to Reproduce:**
 1. Execute 'Test-DscConfiguration -Verbose' on a node that uses rsGit reosurce as part of its configuration
 
**Expected Results:**
The system should come back with either 'true' or 'false' depending on whether the local copy of the repo differs from upstream
 
**Actual Results:**
 The function will always return 'false' and is not in line with the intended use of Test-TargetResource function.

**Comments:**
The issue will be that all managed node that use this resource will always fail and will always fail to pass some automated audits we can throw at them using DSC.

**Comment by leshkinski** [comment]
While the module has been heavily modified, its main functionality remains mostly similar. Key differences are that Test function now validates that your local repository settings (Branch, source, etc) are in line with specified DSC configuration. 

The module will now compare if remote is more up-to-date and ensure that local copy of the repo is always up-to-date, while completely removing local changes or addition. This behavior can be changed by adding the 'Mode = "CopyOnly"' parameter. With this setting, the remote repo will be cloned once and any local changes will persist, while allowing the Test-TargetResource to return $true to ensure correct DSC functionality.

README has been updated to reflect the extra 'Mode' parameter, which is used to define whether you'd like to keep local repo up-to-date and always keep in sync with remote or just clone and allow local changes to persist. As you'll see from the code, it does some verification of configuration settings you define in DSC, so it is now possible to point a DSC-enabled repo to a different branch or a completely new source, and it will be reset.

rsPullServer.ps1 will now require modification for Arnie configuration to persist (just add Mode = "CopyOnly" to PullServer config):

    rsGit Arnie
    {
       name = "Arnie"
       Source = "https://github.com/rsWinAutomationSupport/Arnie.git"
       Destination = "C:\inetpub\wwwroot"
       Ensure = "Present"
       Branch = "staging"
       Mode = "CopyOnly"
    } (edited)

**Comment by leshkinski** [comment]
hi all - my PR to resolve this is still not merged. Is everyone happy for me to merge this?

**Comment by jonathan-madison** [comment]
This has been merged. We've also moved rsGit to be included as part of rsPackageSourceManager.
